# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=150)),
                ('article_text', models.CharField(max_length=10000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
