# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
